global:
  scrape_interval: 15s # 15초마다 데이터 수집

scrape_configs:
  - job_name: 'fastapi-backend'
    static_configs:
      - targets: ['voice-backend:8000'] # 백엔드 서비스 이름과 포트

  - job_name: 'postgres-db'
    static_configs:
      - targets: ['postgres-exporter:9187']
